/**
 * Built-in Symbol Sets Module
 *
 * This module centralizes all built-in symbol sets for different programming languages.
 * It provides fast lookup functions for checking if a symbol is a language built-in,
 * which is essential for validation to avoid false positives when detecting hallucinations.
 *
 * Supported Languages:
 * - Python: Built-in functions, types, exceptions, and standard library modules
 * - JavaScript/TypeScript: Built-in globals, constructors, DOM APIs, and utility types
 *
 * @format
 */

// ============ Python Built-in Symbol Sets ============

/**
 * Python built-in functions, types, and constants
 * Based on Python 3.11+ builtins
 */
export const PYTHON_BUILTINS = new Set([
  // Built-in functions
  "abs",
  "aiter",
  "all",
  "anext",
  "any",
  "ascii",
  "bin",
  "bool",
  "breakpoint",
  "bytearray",
  "bytes",
  "callable",
  "chr",
  "classmethod",
  "compile",
  "complex",
  "delattr",
  "dict",
  "dir",
  "divmod",
  "enumerate",
  "eval",
  "exec",
  "filter",
  "float",
  "format",
  "frozenset",
  "getattr",
  "globals",
  "hasattr",
  "hash",
  "help",
  "hex",
  "id",
  "input",
  "int",
  "isinstance",
  "issubclass",
  "iter",
  "len",
  "list",
  "locals",
  "map",
  "max",
  "memoryview",
  "min",
  "next",
  "object",
  "oct",
  "open",
  "ord",
  "pow",
  "print",
  "property",
  "range",
  "repr",
  "reversed",
  "round",
  "set",
  "setattr",
  "slice",
  "sorted",
  "staticmethod",
  "str",
  "sum",
  "super",
  "tuple",
  "type",
  "vars",
  "zip",
  // Built-in constants
  "True",
  "False",
  "None",
  "Ellipsis",
  "NotImplemented",
  "__debug__",
  "__name__",
  "__doc__",
  "__package__",
  "__loader__",
  "__spec__",
  // Built-in exceptions (common ones)
  "Exception",
  "BaseException",
  "ValueError",
  "TypeError",
  "KeyError",
  "IndexError",
  "AttributeError",
  "ImportError",
  "RuntimeError",
  "StopIteration",
  "GeneratorExit",
  "AssertionError",
  "NameError",
  "ZeroDivisionError",
  "FileNotFoundError",
  "OSError",
  "IOError",
  "PermissionError",
  "TimeoutError",
  "ConnectionError",
  "BrokenPipeError",
  // Special names
  "self",
  "cls",
  // Common typing module types (often used without import in type hints)
  "Any",
  "Union",
  "Optional",
  "List",
  "Dict",
  "Set",
  "Tuple",
  "Callable",
  "Type",
  "Generic",
  "TypeVar",
  "Protocol",
  "Final",
  "Literal",
]);

/**
 * Python built-in types for type hint checking
 */
export const PYTHON_BUILTIN_TYPES = new Set([
  // Basic types
  "int",
  "float",
  "str",
  "bool",
  "bytes",
  "bytearray",
  "list",
  "dict",
  "set",
  "frozenset",
  "tuple",
  "None",
  "type",
  "object",
  // typing module types
  "Any",
  "Union",
  "Optional",
  "List",
  "Dict",
  "Set",
  "FrozenSet",
  "Tuple",
  "Callable",
  "Type",
  "Generic",
  "TypeVar",
  "Protocol",
  "Final",
  "Literal",
  "ClassVar",
  "Annotated",
  "TypeAlias",
  "TypeGuard",
  "ParamSpec",
  "Concatenate",
  "Awaitable",
  "Coroutine",
  "AsyncGenerator",
  "AsyncIterator",
  "AsyncIterable",
  "Iterator",
  "Iterable",
  "Generator",
  "Sequence",
  "Mapping",
  "MutableMapping",
  "MutableSequence",
  "MutableSet",
  "AbstractSet",
  "Collection",
  "Container",
  "Reversible",
  "SupportsInt",
  "SupportsFloat",
  "SupportsComplex",
  "SupportsBytes",
  "SupportsAbs",
  "SupportsRound",
  "Hashable",
  "Sized",
  "IO",
  "TextIO",
  "BinaryIO",
  "Pattern",
  "Match",
  "AnyStr",
  "NoReturn",
  "Never",
  "Self",
  "LiteralString",
  "Unpack",
  "TypeVarTuple",
  "Required",
  "NotRequired",
  "ReadOnly",
  // collections.abc types
  "Hashable",
  "Iterable",
  "Iterator",
  "Reversible",
  "Generator",
  "Container",
  "Collection",
  "Callable",
  "Set",
  "MutableSet",
  "Mapping",
  "MutableMapping",
  "Sequence",
  "MutableSequence",
  "ByteString",
  "Awaitable",
  "Coroutine",
  "AsyncIterable",
  "AsyncIterator",
  "AsyncGenerator",
]);

// ============ JavaScript/TypeScript Built-in Symbol Sets ============

/**
 * JavaScript/TypeScript built-in globals and constructors
 * Based on ECMAScript 2023 and common Node.js/Browser APIs
 */
export const JS_BUILTINS = new Set([
  // Global objects
  "globalThis",
  "Infinity",
  "NaN",
  "undefined",
  // Fundamental objects
  "Object",
  "Function",
  "Boolean",
  "Symbol",
  // Error objects
  "Error",
  "AggregateError",
  "EvalError",
  "RangeError",
  "ReferenceError",
  "SyntaxError",
  "TypeError",
  "URIError",
  // Numbers and dates
  "Number",
  "BigInt",
  "Math",
  "Date",
  // Text processing
  "String",
  "RegExp",
  // Indexed collections
  "Array",
  "Int8Array",
  "Uint8Array",
  "Uint8ClampedArray",
  "Int16Array",
  "Uint16Array",
  "Int32Array",
  "Uint32Array",
  "Float32Array",
  "Float64Array",
  "BigInt64Array",
  "BigUint64Array",
  // Keyed collections
  "Map",
  "Set",
  "WeakMap",
  "WeakSet",
  "WeakRef",
  "FinalizationRegistry",
  // Structured data
  "ArrayBuffer",
  "SharedArrayBuffer",
  "DataView",
  "Atomics",
  "JSON",
  // Control abstraction
  "Promise",
  "Generator",
  "GeneratorFunction",
  "AsyncFunction",
  "AsyncGenerator",
  "AsyncGeneratorFunction",
  // Reflection
  "Reflect",
  "Proxy",
  // Internationalization
  "Intl",
  // Web APIs (common)
  "console",
  "fetch",
  "setTimeout",
  "setInterval",
  "clearTimeout",
  "clearInterval",
  "setImmediate",
  "clearImmediate",
  "queueMicrotask",
  "URL",
  "URLSearchParams",
  "TextEncoder",
  "TextDecoder",
  "AbortController",
  "AbortSignal",
  "FormData",
  "Headers",
  "Request",
  "Response",
  "Blob",
  "File",
  "FileReader",
  "FileList",
  "Event",
  "EventTarget",
  "CustomEvent",
  "document",
  "window",
  "navigator",
  "location",
  "history",
  "localStorage",
  "sessionStorage",
  "WebSocket",
  "Worker",
  "MessageChannel",
  "MessagePort",
  "Crypto",
  "crypto",
  "SubtleCrypto",
  // Node.js globals
  "process",
  "Buffer",
  "global",
  "__dirname",
  "__filename",
  "require",
  "module",
  "exports",
  // Common functions
  "parseInt",
  "parseFloat",
  "isNaN",
  "isFinite",
  "encodeURI",
  "encodeURIComponent",
  "decodeURI",
  "decodeURIComponent",
  "eval",
  "atob",
  "btoa",
  "alert",
  "confirm",
  "prompt",
  "Image",
  "Audio",
  "Option",
  "Notification",
  "Geolocation",
  "Screen",
  "screen",
  "Performance",
  "performance",
  "requestAnimationFrame",
  "cancelAnimationFrame",
  "requestIdleCallback",
  "cancelIdleCallback",
  "IntersectionObserver",
  "ResizeObserver",
  "MutationObserver",
  "Storage",
  "StorageEvent",
  "indexedDB",
  "IDBDatabase",
  "IDBTransaction",
  "IDBCursor",
  "IDBRequest",
  "ServiceWorker",
  "ServiceWorkerContainer",
  "ServiceWorkerRegistration",
  "Cache",
  "CacheStorage",
  "caches",
  "BroadcastChannel",
  "SharedWorker",
  "WorkerGlobalScope",
  "Window",
  "Document",
  "Element",
  "Node",
  "SVGElement",
  "CanvasRenderingContext2D",
  "WebGLRenderingContext",
  "AudioContext",
  "MediaStream",
  "MediaRecorder",
  "URL",
  "URLSearchParams",
  "WebAssembly",
  "SharedArrayBuffer",
  // Common test globals (Jest/Vitest/Mocha)
  "expect",
  "test",
  "it",
  "describe",
  "beforeEach",
  "afterEach",
  "beforeAll",
  "afterAll",
  "vi",
  "jest",
  "fixture",
  // Iterator/Generator
  "Iterator",
  "AsyncIterator",
  // React Hooks and standard React globals
  "React",
  "useState",
  "useEffect",
  "useContext",
  "useReducer",
  "useCallback",
  "useMemo",
  "useRef",
  "useImperativeHandle",
  "useLayoutEffect",
  "useDebugValue",
  "useDeferredValue",
  "useTransition",
  "useId",
  "useSyncExternalStore",
  "useInsertionEffect",
  // Common method names (to avoid flagging standard API usage as hallucinations)
  "append",
  "get",
  "set",
  "has",
  "delete",
  "entries",
  "keys",
  "values",
  "forEach",
  "map",
  "filter",
  "reduce",
  "some",
  "every",
  "find",
  "push",
  "pop",
  "shift",
  "unshift",
  "splice",
  "slice",
  "join",
  "split",
  "includes",
  "indexOf",
  "lastIndexOf",
  "toString",
  "toJSON",
  "then",
  "catch",
  "finally",
  "json",
  "text",
  "blob",
  "status",
  "ok",
  "headers",
  "clone",
  "addEventListener",
  "removeEventListener",
  "dispatchEvent",
  "preventDefault",
  "stopPropagation",
  "getElementById",
  "querySelector",
  "querySelectorAll",
  // Test framework methods (Jest/Vitest)
  "mockReturnValue",
  "mockResolvedValue",
  "mockRejectedValue",
  "mockImplementation",
  "mockClear",
  "mockReset",
  "mockRestore",
  "spyOn",
  "fn",
  // Node.js Namespace
  "NodeJS",
  // Common library variables (Zod, tRPC, Drizzle, Prisma - used so frequently they might as well be built-ins)
  "z", // Zod
  "t", // tRPC
  "db", // Database
  "prisma", // Prisma
  "ctx", // Context
]);

/**
 * Standard HTML tags to avoid false positives in JSX
 */
export const HTML_TAGS = new Set([
  "div",
  "span",
  "p",
  "a",
  "button",
  "input",
  "label",
  "form",
  "ul",
  "ol",
  "li",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "nav",
  "header",
  "footer",
  "main",
  "aside",
  "section",
  "article",
  "table",
  "thead",
  "tbody",
  "tr",
  "th",
  "td",
  "img",
  "br",
  "hr",
  "textarea",
  "select",
  "option",
  "canvas",
  "svg",
  "video",
  "audio",
  "iframe",
  "details",
  "summary",
  "progress",
  "meter",
  "time",
  "mark",
  "cite",
  "code",
  "pre",
  "strong",
  "em",
  "small",
  "i",
  "b",
  "sub",
  "sup",
  "del",
  "ins",
  "kbd",
  "samp",
  "var",
  "q",
  "blockquote",
  "address",
  "dfn",
  "abbr",
  "data",
  "ruby",
  "rt",
  "rp",
  "bdi",
  "bdo",
  "wbr",
  "dl",
  "dt",
  "dd",
  "figure",
  "figcaption",
  "fieldset",
  "legend",
  "template",
  "slot",
  "style",
  "script",
  "link",
  "meta",
  "title",
  "head",
  "html",
  "body",
]);

/**
 * Standard SVG tags to avoid false positives in JSX
 */
export const SVG_TAGS = new Set([
  "svg",
  "path",
  "g",
  "circle",
  "rect",
  "line",
  "polyline",
  "polygon",
  "ellipse",
  "text",
  "tspan",
  "defs",
  "use",
  "symbol",
  "marker",
  "linearGradient",
  "radialGradient",
  "stop",
  "clipPath",
  "mask",
  "filter",
  "feGaussianBlur",
  "feOffset",
  "feMerge",
  "feMergeNode",
  "feColorMatrix",
  "feComponentTransfer",
  "feFuncR",
  "feFuncG",
  "feFuncB",
  "feFuncA",
  "feComposite",
  "feFlood",
  "feTile",
  "feTurbulence",
  "feDisplacementMap",
  "feMorphology",
  "feSpecularLighting",
  "feDiffuseLighting",
  "fePointLight",
  "feDistantLight",
  "feSpotLight",
  "image",
  "foreignObject",
]);

/**
 * TypeScript built-in types (for type reference checking)
 */
export const TS_BUILTIN_TYPES = new Set([
  // Primitive types
  "string",
  "number",
  "boolean",
  "null",
  "undefined",
  "void",
  "never",
  "any",
  "unknown",
  "object",
  "symbol",
  "bigint",
  // Wrapper types
  "String",
  "Number",
  "Boolean",
  "Object",
  "Function",
  "Symbol",
  "BigInt",
  // Collections
  "Array",
  "Map",
  "Set",
  "WeakMap",
  "WeakSet",
  "Promise",
  "ReadonlyArray",
  "ReadonlyMap",
  "ReadonlySet",
  // Utility types
  "Partial",
  "Required",
  "Readonly",
  "Record",
  "Pick",
  "Omit",
  "Exclude",
  "Extract",
  "NonNullable",
  "Parameters",
  "ReturnType",
  "ConstructorParameters",
  "InstanceType",
  "ThisType",
  "ThisParameterType",
  "OmitThisParameter",
  "Uppercase",
  "Lowercase",
  "Capitalize",
  "Uncapitalize",
  "Awaited",
  "NoInfer",
  // DOM types (common)
  "HTMLElement",
  "Element",
  "Node",
  "Document",
  "Window",
  "Event",
  "MouseEvent",
  "KeyboardEvent",
  "TouchEvent",
  "FocusEvent",
  "HTMLInputElement",
  "HTMLButtonElement",
  "HTMLDivElement",
  "HTMLFormElement",
  "HTMLAnchorElement",
  "HTMLImageElement",
  "HTMLSelectElement",
  "HTMLTextAreaElement",
  "NodeList",
  "HTMLCollection",
  "DOMTokenList",
  // React types (common)
  "React",
  "ReactNode",
  "ReactElement",
  "JSX",
  "FC",
  "Component",
  "useState",
  "useEffect",
  "useCallback",
  "useMemo",
  "useRef",
  "useContext",
  "PropsWithChildren",
  "ComponentProps",
  "ComponentType",
  // Node types
  "Buffer",
  "NodeJS",
  // Error types
  "Error",
  "TypeError",
  "RangeError",
  "SyntaxError",
  "ReferenceError",
  // Iterator types
  "Iterator",
  "IterableIterator",
  "AsyncIterator",
  "AsyncIterableIterator",
  "Generator",
  "AsyncGenerator",
  "NodeJS",
]);

/**
 * Get Node.js built-in modules.
 *
 * @returns A Set of Node.js built-In module names
 */
export function getNodeBuiltInModules(): Set<string> {
  return NODE_BUILTIN_MODULES;
}

/**
 * Node.js built-in modules
 * Based on Node.js 20+ documentation
 */
export const NODE_BUILTIN_MODULES = new Set([
  "assert",
  "async_hooks",
  "buffer",
  "child_process",
  "cluster",
  "console",
  "constants",
  "crypto",
  "dgram",
  "diagnostics_channel",
  "dns",
  "domain",
  "events",
  "fs",
  "fs/promises",
  "http",
  "http2",
  "https",
  "inspector",
  "module",
  "net",
  "os",
  "path",
  "path/posix",
  "path/win32",
  "perf_hooks",
  "process",
  "punycode",
  "querystring",
  "readline",
  "repl",
  "stream",
  "stream/consumers",
  "stream/promises",
  "stream/web",
  "string_decoder",
  "sys",
  "timers",
  "timers/promises",
  "tls",
  "trace_events",
  "tty",
  "url",
  "util",
  "v8",
  "vm",
  "wasi",
  "worker_threads",
  "zlib",
]);

// ============ Helper Functions ============

/**
 * Check if a name is a Python built-in function, type, or constant.
 * @param name - The symbol name to check
 * @returns true if the name is a Python built-in
 */
export function isPythonBuiltin(name: string): boolean {
  return (
    PYTHON_BUILTINS.has(name) ||
    PYTHON_BUILTIN_TYPES.has(name) ||
    PYTHON_COMMON_METHODS.has(name)
  );
}

/**
 * Common method names from popular libraries that should not be flagged as hallucinations.
 * These are methods that are commonly returned by library functions but not tracked in our symbol table.
 */
export const COMMON_LIBRARY_METHODS = new Set([
  // React DOM methods
  "render",
  "unmount",
  "hydrate",
  // Array/Collection methods (JavaScript built-ins)
  "push",
  "pop",
  "shift",
  "unshift",
  "slice",
  "splice",
  "concat",
  "join",
  "reverse",
  "sort",
  "filter",
  "map",
  "reduce",
  "reduceRight",
  "forEach",
  "find",
  "findIndex",
  "findLast",
  "findLastIndex",
  "some",
  "every",
  "includes",
  "indexOf",
  "lastIndexOf",
  "flat",
  "flatMap",
  "fill",
  "copyWithin",
  "entries",
  "keys",
  "values",
  "at",
  "toReversed",
  "toSorted",
  "toSpliced",
  "with",
  // String methods
  "charAt",
  "charCodeAt",
  "codePointAt",
  "endsWith",
  "startsWith",
  "toLowerCase",
  "toUpperCase",
  "trim",
  "trimStart",
  "trimEnd",
  "padStart",
  "padEnd",
  "repeat",
  "replace",
  "replaceAll",
  "split",
  "substring",
  "substr",
  "match",
  "matchAll",
  "search",
  "localeCompare",
  "normalize",
  "isWellFormed",
  "toWellFormed",
  // Object methods
  "toString",
  "toLocaleString",
  "valueOf",
  "hasOwnProperty",
  "isPrototypeOf",
  "propertyIsEnumerable",
  // Map/Set methods
  "get",
  "set",
  "has",
  "delete",
  "clear",
  "add",
  "size",
  // Promise methods
  "then",
  "catch",
  "finally",
  // Date methods
  "getTime",
  "getFullYear",
  "getMonth",
  "getDate",
  "getDay",
  "getHours",
  "getMinutes",
  "getSeconds",
  "getMilliseconds",
  "toISOString",
  "toDateString",
  "toTimeString",
  "toJSON",
  // Number methods
  "toExponential",
  "toFixed",
  "toPrecision",
  // DOM methods
  "addEventListener",
  "removeEventListener",
  "dispatchEvent",
  "appendChild",
  "removeChild",
  "insertBefore",
  "replaceChild",
  "cloneNode",
  "contains",
  "querySelector",
  "querySelectorAll",
  "getElementById",
  "getElementsByClassName",
  "getElementsByTagName",
  "setAttribute",
  "getAttribute",
  "removeAttribute",
  "hasAttribute",
  "classList",
  "focus",
  "blur",
  "click",
  "submit",
  "reset",
  "scrollIntoView",
  "getBoundingClientRect",
  "getComputedStyle",
  // Event/DOM specifics (Vibe whitelisting)
  "preventDefault",
  "stopPropagation",
  "stopImmediatePropagation",
  "persist",
  // Date specifics
  "setDate",
  "setFullYear",
  "setHours",
  "setMinutes",
  "setSeconds",
  "setMilliseconds",
  "setMonth",
  "setTime",
  "setUTCDate",
  "setUTCFullYear",
  "setUTCHours",
  "setUTCMilliseconds",
  "setUTCMinutes",
  "setUTCMonth",
  "setUTCSeconds",
  // Common library methods
  "subscribe",
  "unsubscribe",
  "dispatch",
  "getState",
  "connect",
  "disconnect",
  "on",
  "off",
  "emit",
  "once",
  "pipe",
  "tap",
  "debounce",
  "throttle",
  "clone",
  "merge",
  "extend",
  "assign",
  "pick",
  "omit",
  "defaults",
  "isEqual",
  "isEmpty",
  "isArray",
  "isObject",
  "isString",
  "isNumber",
  "isBoolean",
  "isFunction",
  "isNull",
  "isUndefined",
  "isDefined",
  "isNaN",
  "isFinite",
]);

/**
 * Common Python methods to whitelist globally to reduce noise
 */
export const PYTHON_COMMON_METHODS = new Set([
  "append",
  "extend",
  "insert",
  "remove",
  "pop",
  "clear",
  "index",
  "count",
  "sort",
  "reverse",
  "copy",
  "items",
  "keys",
  "values",
  "update",
  "get",
  "popitem",
  "setdefault",
  "fromkeys",
  "add",
  "discard",
  "difference",
  "intersection",
  "isdisjoint",
  "issubset",
  "issuperset",
  "symmetric_difference",
  "union",
  "capitalize",
  "casefold",
  "center",
  "encode",
  "endswith",
  "expandtabs",
  "find",
  "format",
  "format_map",
  "isalnum",
  "isalpha",
  "isascii",
  "isdecimal",
  "isdigit",
  "isidentifier",
  "islower",
  "isnumeric",
  "isprintable",
  "isspace",
  "istitle",
  "isupper",
  "join",
  "ljust",
  "lower",
  "lstrip",
  "maketrans",
  "partition",
  "removeprefix",
  "removesuffix",
  "rfind",
  "rindex",
  "rjust",
  "rpartition",
  "rsplit",
  "rstrip",
  "splitlines",
  "startswith",
  "strip",
  "swapcase",
  "title",
  "translate",
  "upper",
  "zfill",
  "read",
  "readline",
  "readlines",
  "write",
  "writelines",
  "seek",
  "tell",
  "flush",
  "close",
  "with_traceback",
  "strftime",
  "isoformat",
  "timestamp",
  "weekday",
  "isoweekday",
  "astimezone",
  "replace",
]);

/**
 * Check if a name is a JavaScript built-in global or constructor.
 * @param name - The symbol name to check
 * @returns true if the name is a JavaScript built-in
 */
export function isJSBuiltin(name: string): boolean {
  return (
    JS_BUILTINS.has(name) ||
    HTML_TAGS.has(name) ||
    SVG_TAGS.has(name) ||
    COMMON_LIBRARY_METHODS.has(name)
  );
}

/**
 * Check if a name is a Python built-in type (for type hint checking).
 * @param name - The type name to check
 * @returns true if the name is a Python built-in type
 */
export function isPythonBuiltinType(name: string): boolean {
  return PYTHON_BUILTIN_TYPES.has(name);
}

/**
 * Check if a name is a TypeScript built-in type.
 * @param name - The type name to check
 * @returns true if the name is a TypeScript built-in type
 */
export function isTSBuiltinType(name: string): boolean {
  return TS_BUILTIN_TYPES.has(name);
}

/**
 * Get Python standard library modules.
 * This is a comprehensive list based on Python 3.11+ documentation.
 * Organized by category for maintainability.
 *
 * @returns A Set of Python standard library module names
 */
export function getPythonStdLib(): Set<string> {
  const modules: string[] = [
    // Text Processing
    "string",
    "re",
    "difflib",
    "textwrap",
    "unicodedata",
    "stringprep",
    "readline",
    "rlcompleter",
    // Binary Data Services
    "struct",
    "codecs",
    // Data Types
    "datetime",
    "zoneinfo",
    "calendar",
    "collections",
    "heapq",
    "bisect",
    "array",
    "weakref",
    "types",
    "copy",
    "pprint",
    "reprlib",
    "enum",
    "graphlib",
    // Numeric and Mathematical
    "numbers",
    "math",
    "cmath",
    "decimal",
    "fractions",
    "random",
    "statistics",
    // Functional Programming
    "itertools",
    "functools",
    "operator",
    // File and Directory Access
    "pathlib",
    "os",
    "fileinput",
    "stat",
    "filecmp",
    "tempfile",
    "glob",
    "fnmatch",
    "linecache",
    "shutil",
    // Data Persistence
    "pickle",
    "copyreg",
    "shelve",
    "marshal",
    "dbm",
    "sqlite3",
    // Data Compression
    "zlib",
    "gzip",
    "bz2",
    "lzma",
    "zipfile",
    "tarfile",
    // File Formats
    "csv",
    "configparser",
    "tomllib",
    "netrc",
    "plistlib",
    // Cryptographic Services
    "hashlib",
    "hmac",
    "secrets",
    // Generic OS Services
    "sys",
    "sysconfig",
    "builtins",
    "warnings",
    "dataclasses",
    "contextlib",
    "abc",
    "atexit",
    "traceback",
    "gc",
    "inspect",
    "site",
    // Concurrent Execution
    "threading",
    "multiprocessing",
    "concurrent",
    "subprocess",
    "sched",
    "queue",
    "contextvars",
    // Networking and IPC
    "asyncio",
    "socket",
    "ssl",
    "select",
    "selectors",
    "signal",
    "mmap",
    // Internet Data Handling
    "email",
    "json",
    "mailbox",
    "mimetypes",
    "base64",
    "binascii",
    "quopri",
    // Structured Markup
    "html",
    "xml",
    // Internet Protocols
    "webbrowser",
    "wsgiref",
    "urllib",
    "http",
    "ftplib",
    "poplib",
    "imaplib",
    "smtplib",
    "uuid",
    "socketserver",
    "xmlrpc",
    "ipaddress",
    // Multimedia
    "wave",
    "colorsys",
    // Internationalization
    "gettext",
    "locale",
    // Program Frameworks
    "turtle",
    "cmd",
    "shlex",
    // GUI
    "tkinter",
    "idlelib",
    // Development Tools
    "typing",
    "pydoc",
    "doctest",
    "unittest",
    "test",
    // Debugging and Profiling
    "bdb",
    "faulthandler",
    "pdb",
    "timeit",
    "trace",
    "tracemalloc",
    // Software Packaging
    "ensurepip",
    "venv",
    "zipapp",
    // Python Runtime
    "importlib",
    "runpy",
    "ast",
    "symtable",
    "token",
    "keyword",
    "tokenize",
    "tabnanny",
    "pyclbr",
    "py_compile",
    "compileall",
    "dis",
    "pickletools",
    // Custom Interpreters
    "code",
    "codeop",
    // Importing
    "zipimport",
    "pkgutil",
    "modulefinder",
    // Unix Specific
    "posix",
    "pwd",
    "grp",
    "termios",
    "tty",
    "pty",
    "fcntl",
    "resource",
    "syslog",
    // Windows Specific
    "msvcrt",
    "winreg",
    "winsound",
    // Logging
    "logging",
    // Argument Parsing
    "argparse",
    "getopt",
    "optparse",
    // Common third-party that feel like stdlib
    "typing_extensions",
  ];
  return new Set(modules);
}
