# Pydantic schemas

from .activity import ActivityBase, ActivityCreate, ActivityListResponse, ActivityResponse
from .auth import (
    OAuthCallback,
    OAuthLoginResponse,
    OAuthTokenResponse,
    OAuthUser,
    OTPRequest,
    OTPVerify,
    Token,
    TokenData,
    TokenPair,
    TokenRefresh,
    UserBase,
    UserCreate,
    UserLogin,
)
from .change_request import (
    ChangeRequestApprove,
    ChangeRequestBase,
    ChangeRequestComplete,
    ChangeRequestCreate,
    ChangeRequestReject,
    ChangeRequestResponse,
    ChangeRequestUpdate,
)
from .client import ClientBase, ClientCreate, ClientResponse, ClientUpdate
from .client_portal import (
    ClientPortalAccessRequest,
    ClientPortalAccessResponse,
    ClientPortalDashboard,
    ClientPortalLogout,
    ClientPortalSession,
    ClientPortalTokenValidation,
)
from .contract import (
    ContractGenerate,
    ContractSend,
    ContractSign,
    ContractSignatureBase,
    ContractSignatureCreate,
    ContractSignatureResponse,
    ContractTemplateBase,
    ContractTemplateCreate,
    ContractTemplateResponse,
    ContractTemplateUpdate,
    ContractUpload,
)
from .deliverable import DeliverableBase, DeliverableCreate, DeliverableResponse, DeliverableUpdate, DeliverableVerification
from .git_integration import (
    AccessControlRequest,
    AccessControlResponse,
    BitbucketWebhookPayload,
    GitHubWebhookPayload,
    GitLabWebhookPayload,
    PRStatusRequest,
    PRStatusResponse,
    RepositoryValidateRequest,
    RepositoryValidateResponse,
    WebhookSetupRequest,
    WebhookSetupResponse,
)
from .notification import (
    NotificationBase,
    NotificationCreate,
    NotificationListResponse,
    NotificationResponse,
    UnreadCountResponse,
)
from .payment import (
    InvoiceBase,
    InvoiceCreate,
    InvoiceLineItem,
    InvoiceMarkPaid,
    InvoiceResponse,
    InvoiceSend,
    InvoiceUpdate,
    InvoiceVerifyPayment,
    PaymentInitialize,
    PaymentInitializeResponse,
    PaystackBank,
    PaystackSubaccountCreate,
    PaystackSubaccountResponse,
    PaystackSubaccountUpdate,
    PaystackWebhook,
    PaystackWebhookData,
)
from .project import ProjectCreate, ProjectMetrics, ProjectResponse, ProjectUpdate, ScopeGuardrailConfig
from .settings import ProfileImageUpload, UserSettingsBase, UserSettingsResponse, UserSettingsUpdate
from .subscription import (
    SubscriptionCancel,
    SubscriptionCreate,
    SubscriptionFeatures,
    SubscriptionPlan,
    SubscriptionPlanBase,
    SubscriptionResponse,
    SubscriptionUpdate,
)
from .template import ProjectTemplateBase, ProjectTemplateCreate, ProjectTemplateResponse, ProjectTemplateUpdate, TemplateUse
from .time_entry import TimeEntryBase, TimeEntryCreate, TimeEntryResponse, TimeEntrySummary, TimeEntryUpdate

__all__ = [
    # Auth
    "UserBase",
    "UserCreate",
    "UserLogin",
    "Token",
    "TokenData",
    "OTPRequest",
    "OTPVerify",
    "OAuthLoginResponse",
    "OAuthCallback",
    "OAuthUser",
    "OAuthTokenResponse",
    "TokenRefresh",
    "TokenPair",
    # Client
    "ClientBase",
    "ClientCreate",
    "ClientUpdate",
    "ClientResponse",
    # Project
    "ScopeGuardrailConfig",
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectResponse",
    "ProjectMetrics",
    # Deliverable
    "DeliverableBase",
    "DeliverableCreate",
    "DeliverableUpdate",
    "DeliverableResponse",
    "DeliverableVerification",
    # Time Entry
    "TimeEntryBase",
    "TimeEntryCreate",
    "TimeEntryUpdate",
    "TimeEntryResponse",
    "TimeEntrySummary",
    # Contract
    "ContractTemplateBase",
    "ContractTemplateCreate",
    "ContractTemplateUpdate",
    "ContractTemplateResponse",
    "ContractGenerate",
    "ContractUpload",
    "ContractSend",
    "ContractSignatureBase",
    "ContractSignatureCreate",
    "ContractSign",
    "ContractSignatureResponse",
    # Payment
    "InvoiceLineItem",
    "InvoiceBase",
    "InvoiceCreate",
    "InvoiceUpdate",
    "InvoiceResponse",
    "InvoiceSend",
    "InvoiceMarkPaid",
    "InvoiceVerifyPayment",
    "PaystackSubaccountCreate",
    "PaystackSubaccountUpdate",
    "PaystackSubaccountResponse",
    "PaystackBank",
    "PaymentInitialize",
    "PaymentInitializeResponse",
    "PaystackWebhook",
    "PaystackWebhookData",
    # Subscription
    "SubscriptionPlanBase",
    "SubscriptionPlan",
    "SubscriptionCreate",
    "SubscriptionUpdate",
    "SubscriptionResponse",
    "SubscriptionCancel",
    "SubscriptionFeatures",
    # Change Request
    "ChangeRequestBase",
    "ChangeRequestCreate",
    "ChangeRequestUpdate",
    "ChangeRequestResponse",
    "ChangeRequestApprove",
    "ChangeRequestReject",
    "ChangeRequestComplete",
    # Template
    "ProjectTemplateBase",
    "ProjectTemplateCreate",
    "ProjectTemplateUpdate",
    "ProjectTemplateResponse",
    "TemplateUse",
    # Settings
    "UserSettingsBase",
    "UserSettingsUpdate",
    "UserSettingsResponse",
    "ProfileImageUpload",
    # Client Portal
    "ClientPortalAccessRequest",
    "ClientPortalAccessResponse",
    "ClientPortalTokenValidation",
    "ClientPortalSession",
    "ClientPortalDashboard",
    "ClientPortalLogout",
    # Git Integration
    "RepositoryValidateRequest",
    "RepositoryValidateResponse",
    "WebhookSetupRequest",
    "WebhookSetupResponse",
    "AccessControlRequest",
    "AccessControlResponse",
    "PRStatusRequest",
    "PRStatusResponse",
    "GitHubWebhookPayload",
    "GitLabWebhookPayload",
    "BitbucketWebhookPayload",
    # Activity
    "ActivityBase",
    "ActivityCreate",
    "ActivityResponse",
    "ActivityListResponse",
    # Notification
    "NotificationBase",
    "NotificationCreate",
    "NotificationResponse",
    "NotificationListResponse",
    "UnreadCountResponse",
]
