"""add_oauth_fields

Revision ID: 80f6c28b6114
Revises: f28b91a3872b
Create Date: 2025-10-12 16:56:57.646103

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80f6c28b6114"
down_revision: Union[str, None] = "f28b91a3872b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if columns already exist before adding them (SQLite issue)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col["name"] for col in inspector.get_columns("users")]

    if "provider" not in columns:
        op.add_column("users", sa.Column("provider", sa.String(), nullable=True))
    if "provider_id" not in columns:
        op.add_column("users", sa.Column("provider_id", sa.String(), nullable=True))
    if "provider_data" not in columns:
        op.add_column("users", sa.Column("provider_data", sa.Text(), nullable=True))
    # Note: SQLite doesn't support ALTER TABLE for NOT NULL constraints, so we skip this
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "hashed_password", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("users", "provider_data")
    op.drop_column("users", "provider_id")
    op.drop_column("users", "provider")
    # ### end Alembic commands ###
