import asyncio
import os
import sys
from pathlib import Path

# Add parent directory to path to import app modules
sys.path.append(str(Path(__file__).parent.parent))

# Manually load env if needed, though app.core.config might do it
from dotenv import load_dotenv

load_dotenv()


async def test_pdf_and_email():
    print("=== STARTING TEST: PDF GENERATION AND EMAIL ===")

    print("\n1. Testing WeasyPrint import...")
    try:
        from weasyprint import HTML

        print("   ✓ WeasyPrint imported successfully.")
    except Exception as e:
        print(f"   ✗ FAILED to import WeasyPrint: {e}")
        return

    print("\n2. Testing PDF Generation...")
    try:
        html_content = """
        <html>
            <head>
                <style>
                    body { font-family: sans-serif; padding: 20px; }
                    h1 { color: #333; }
                    .box { border: 1px solid #ccc; padding: 10px; background: #f9f9f9; }
                </style>
            </head>
            <body>
                <h1>Test PDF</h1>
                <div class="box">
                    <p>This is a test PDF generated by DevHQ script.</p>
                    <p>Generated at: %s</p>
                </div>
            </body>
        </html>
        """
        from datetime import datetime

        html_content = html_content % datetime.now()

        pdf_bytes = HTML(string=html_content).write_pdf()
        print(f"   ✓ PDF generated successfully. Size: {len(pdf_bytes)} bytes")

        # Save to file for verification
        output_path = "test_output.pdf"
        with open(output_path, "wb") as f:
            f.write(pdf_bytes)
        print(f"   ✓ Saved locally to {output_path}")

    except Exception as e:
        print(f"   ✗ FAILED to generate PDF: {e}")
        import traceback

        traceback.print_exc()
        return

    print("\n3. Testing Cloudinary Upload...")
    to_email = "codegoddy@gmail.com"

    try:
        # Initialize Cloudinary
        import cloudinary
        import cloudinary.uploader

        from app.utils.cloudinary_client import init_cloudinary

        init_cloudinary()
        print("   ✓ Cloudinary initialized.")

        # Upload
        print("   Uploading to Cloudinary...")
        upload_result = cloudinary.uploader.upload(
            output_path,
            resource_type="raw",
            folder="devhq/test",
            public_id="test_pdf_gen",
            overwrite=True,
        )
        pdf_url = upload_result.get("secure_url")
        print(f"   ✓ Uploaded to: {pdf_url}")

    except Exception as e:
        print(f"   ✗ FAILED to upload to Cloudinary: {e}")
        import traceback

        traceback.print_exc()
        return

    print("\n4. Testing Email Sending with Attachment...")
    try:
        from app.utils.email import send_email

        print(f"   Sending email to {to_email}...")
        result = await send_email(
            to_email=to_email,
            subject="DevHQ Test PDF Generation",
            html_content=f"<p>Please find the attached test PDF.</p><p>PDF URL: <a href='{pdf_url}'>{pdf_url}</a></p>",
            attachment_url=pdf_url,
            attachment_name="test_generated.pdf",
        )

        if result:
            print("   ✓ Email sent successfully!")
        else:
            print("   ✗ Email sending returned None/False")

    except Exception as e:
        print(f"   ✗ FAILED to send email: {e}")
        import traceback

        traceback.print_exc()

    print("\n=== TEST COMPLETED ===")


if __name__ == "__main__":
    asyncio.run(test_pdf_and_email())
